import "./globals.css";
import type { Metadata } from "next";
import { Mulish, Oswald } from "next/font/google";


const muli = Mulish({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${muli.className} ${oswald.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
